name: Push on commit

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Send Push Notification
      uses: techulus/push-github-action@1.0.0
      env:
        API_KEY: ${{ cde3eb76-de08-47b5-a3d9-3a457686e878 }}
        MESSAGE: "There is a new commit!"
